export const HEALTH_AREAS = [
  {
    id: "lungs",
    label: "Lungs",
    icon: "🫁",
    tagline: "Breathing capacity & respiratory efficiency",
    color: "#3B82F6",
    gradient: "linear-gradient(135deg, #EFF6FF 0%, #DBEAFE 100%)",
    fields: [
      {
        key: "breathlessness",
        label: "Do you get breathless during light activity (e.g. walking upstairs)?",
        type: "select",
        options: ["Never", "Rarely", "Sometimes", "Often", "Always"],
      },
      {
        key: "smokingHistory",
        label: "Smoking history",
        type: "select",
        options: [
          "Never smoked",
          "Ex-smoker (quit > 5 years ago)",
          "Ex-smoker (quit < 5 years ago)",
          "Current smoker (< 10 cigarettes/day)",
          "Current smoker (≥ 10 cigarettes/day)",
        ],
      },
      {
        key: "packYears",
        label: "Pack-years smoked (packs/day × years smoked) — enter 0 if non-smoker",
        type: "number",
        placeholder: "e.g. 10",
      },
      {
        key: "aerobicExercise",
        label: "How many minutes of aerobic exercise per week?",
        type: "select",
        options: ["None", "< 60 min", "60–150 min", "150–300 min", "> 300 min"],
      },
      {
        key: "occupationalExposure",
        label: "Occupational dust/chemical exposure?",
        type: "select",
        options: [
          "None",
          "Mild (office with occasional outdoor work)",
          "Moderate (construction, farming)",
          "Heavy (mining, chemical plant)",
        ],
      },
      {
        key: "chronicCough",
        label: "Do you have a chronic cough or produce phlegm?",
        type: "select",
        options: ["No", "Occasional dry cough", "Regular cough", "Cough with phlegm daily"],
      },
    ],
  },
  {
    id: "heart",
    label: "Heart",
    icon: "❤️",
    tagline: "Cardiovascular risk & heart health",
    color: "#EF4444",
    gradient: "linear-gradient(135deg, #FFF1F2 0%, #FFE4E6 100%)",
    fields: [
      {
        key: "systolicBP",
        label: "Systolic blood pressure (top number, mmHg)",
        type: "number",
        placeholder: "e.g. 120",
      },
      {
        key: "diastolicBP",
        label: "Diastolic blood pressure (bottom number, mmHg)",
        type: "number",
        placeholder: "e.g. 80",
      },
      {
        key: "totalCholesterol",
        label: "Total cholesterol in mg/dL — type Unknown if not tested",
        type: "text",
        placeholder: "e.g. 190 or Unknown",
      },
      {
        key: "ldl",
        label: "LDL cholesterol in mg/dL — type Unknown if not tested",
        type: "text",
        placeholder: "e.g. 110 or Unknown",
      },
      {
        key: "cardioExercise",
        label: "Cardio exercise frequency",
        type: "select",
        options: [
          "Sedentary (< 30 min/week)",
          "Light (30–90 min/week)",
          "Moderate (90–150 min/week)",
          "Active (150–300 min/week)",
          "Very active (> 300 min/week)",
        ],
      },
      {
        key: "familyHistory",
        label: "Family history of heart disease before age 65?",
        type: "select",
        options: ["No", "One parent", "Both parents", "Sibling", "Multiple relatives"],
      },
      {
        key: "diabetes",
        label: "Diabetes status",
        type: "select",
        options: ["No diabetes", "Pre-diabetes", "Type 2 diabetes", "Type 1 diabetes"],
      },
      {
        key: "smoking",
        label: "Current smoking status",
        type: "select",
        options: ["Non-smoker", "Ex-smoker", "Current smoker"],
      },
    ],
  },
  {
    id: "nutrition",
    label: "Nutrition",
    icon: "🥗",
    tagline: "Nutrient gaps & dietary balance",
    color: "#10B981",
    gradient: "linear-gradient(135deg, #ECFDF5 0%, #D1FAE5 100%)",
    fields: [
      {
        key: "dietType",
        label: "Primary diet pattern",
        type: "select",
        options: [
          "Omnivore (eat everything)",
          "Flexitarian (mostly plant-based)",
          "Pescatarian (fish, no meat)",
          "Vegetarian (no meat/fish)",
          "Vegan (no animal products)",
          "Keto / Very low carb",
          "Mediterranean",
          "Paleo",
        ],
      },
      {
        key: "fruitsVegetables",
        label: "Daily servings of fruits and vegetables combined",
        type: "select",
        options: ["0–1 servings", "2–3 servings", "4–5 servings", "6–8 servings", "> 8 servings"],
      },
      {
        key: "processedFood",
        label: "How often do you eat ultra-processed foods?",
        type: "select",
        options: ["Rarely / never", "Once or twice a week", "3–4 times a week", "Daily", "Most meals"],
      },
      {
        key: "waterIntake",
        label: "Daily water intake",
        type: "select",
        options: ["< 1 litre", "1–1.5 litres", "1.5–2 litres", "2–2.5 litres", "> 2.5 litres"],
      },
      {
        key: "currentSupplements",
        label: "Current supplements — list all or type None",
        type: "text",
        placeholder: "e.g. Vitamin D 1000 IU, Omega-3, Magnesium",
      },
      {
        key: "healthConditions",
        label: "Health conditions affecting nutrition",
        type: "text",
        placeholder: "e.g. IBS, anaemia, celiac, diabetes, or None",
      },
      {
        key: "energyLevels",
        label: "How are your energy levels throughout the day?",
        type: "select",
        options: [
          "Consistently high",
          "Good with minor dips",
          "Moderate — noticeable afternoon slump",
          "Low most of the day",
          "Exhausted most of the time",
        ],
      },
    ],
  },
  {
    id: "sleep",
    label: "Sleep",
    icon: "🌙",
    tagline: "Sleep quality, duration & recovery",
    color: "#8B5CF6",
    gradient: "linear-gradient(135deg, #F5F3FF 0%, #EDE9FE 100%)",
    fields: [
      {
        key: "sleepDuration",
        label: "Average nightly sleep duration",
        type: "select",
        options: ["< 5 hours", "5–6 hours", "6–7 hours", "7–8 hours", "8–9 hours", "> 9 hours"],
      },
      {
        key: "sleepQuality",
        label: "How would you rate your sleep quality overall?",
        type: "select",
        options: ["Very poor", "Poor", "Fair", "Good", "Excellent"],
      },
      {
        key: "timeToFallAsleep",
        label: "How long does it typically take to fall asleep?",
        type: "select",
        options: ["< 5 minutes", "5–15 minutes", "15–30 minutes", "30–60 minutes", "> 60 minutes"],
      },
      {
        key: "nightWaking",
        label: "How often do you wake during the night?",
        type: "select",
        options: ["Never", "Once occasionally", "Once most nights", "2–3 times a night", "> 3 times a night"],
      },
      {
        key: "issues",
        label: "Sleep issues — list any or type None",
        type: "text",
        placeholder: "e.g. insomnia, snoring, sleep apnea, restless legs, or None",
      },
      {
        key: "screenTime",
        label: "Screen use within 1 hour of bedtime",
        type: "select",
        options: ["Never", "Rarely", "A few times a week", "Most nights", "Every night"],
      },
      {
        key: "caffeine",
        label: "Last caffeine consumption each day",
        type: "select",
        options: [
          "No caffeine",
          "Before noon",
          "Early afternoon (noon–2pm)",
          "Mid afternoon (2–4pm)",
          "Late afternoon or evening (after 4pm)",
        ],
      },
    ],
  },
  {
    id: "muscles",
    label: "Muscles & Joints",
    icon: "💪",
    tagline: "Strength, mobility & pain assessment",
    color: "#F59E0B",
    gradient: "linear-gradient(135deg, #FFFBEB 0%, #FEF3C7 100%)",
    fields: [
      {
        key: "strengthTraining",
        label: "Resistance/strength training frequency",
        type: "select",
        options: ["Never", "1 day/week", "2 days/week", "3 days/week", "4+ days/week"],
      },
      {
        key: "flexibilityHabits",
        label: "Stretching or flexibility practice",
        type: "select",
        options: ["Never", "Rarely (< once a week)", "1–2 times/week", "3–4 times/week", "Daily"],
      },
      {
        key: "painAreas",
        label: "Current pain or discomfort areas",
        type: "text",
        placeholder: "e.g. lower back, left knee, shoulders, or None",
      },
      {
        key: "painLevel",
        label: "Average pain intensity (0 = none, 10 = severe)",
        type: "select",
        options: [
          "0 — No pain",
          "1–2 — Minimal",
          "3–4 — Mild",
          "5–6 — Moderate",
          "7–8 — Severe",
          "9–10 — Debilitating",
        ],
      },
      {
        key: "mobilityLimitations",
        label: "Any mobility limitations?",
        type: "text",
        placeholder: "e.g. can't fully bend knee, limited shoulder rotation, or None",
      },
      {
        key: "dailyActivity",
        label: "Daily activity level outside of exercise",
        type: "select",
        options: [
          "Mostly sedentary (desk job, < 5,000 steps)",
          "Light activity (5,000–7,500 steps)",
          "Moderate (7,500–10,000 steps)",
          "Active (10,000–15,000 steps)",
          "Very active (> 15,000 steps)",
        ],
      },
      {
        key: "injuries",
        label: "Recent or recurring injuries in the past 12 months",
        type: "text",
        placeholder: "e.g. rotator cuff strain, sprained ankle, or None",
      },
    ],
  },
  {
    id: "mental",
    label: "Mental Wellness",
    icon: "🧠",
    tagline: "Stress, mood & psychological resilience",
    color: "#06B6D4",
    gradient: "linear-gradient(135deg, #ECFEFF 0%, #CFFAFE 100%)",
    fields: [
      {
        key: "stressLevel",
        label: "Average daily stress level (1 = very low, 10 = extremely high)",
        type: "select",
        options: ["1–2 — Very low", "3–4 — Low", "5–6 — Moderate", "7–8 — High", "9–10 — Extreme"],
      },
      {
        key: "moodConsistency",
        label: "How consistent is your mood day to day?",
        type: "select",
        options: [
          "Very stable",
          "Mostly stable with minor fluctuations",
          "Moderate swings",
          "Frequent mood swings",
          "Highly unpredictable",
        ],
      },
      {
        key: "anxietyFrequency",
        label: "How often do you experience anxiety or worry?",
        type: "select",
        options: ["Rarely / never", "Occasionally (once a month)", "Weekly", "Several times a week", "Daily"],
      },
      {
        key: "mindfulnessPractice",
        label: "Mindfulness, meditation, or relaxation practice",
        type: "select",
        options: ["None", "Occasionally (< once/week)", "1–2 times/week", "3–4 times/week", "Daily"],
      },
      {
        key: "socialConnection",
        label: "How satisfied are you with your social connections?",
        type: "select",
        options: ["Very satisfied", "Satisfied", "Neutral", "Somewhat isolated", "Very isolated / lonely"],
      },
      {
        key: "workLifeBalance",
        label: "Work-life balance rating",
        type: "select",
        options: ["Excellent", "Good", "Fair", "Poor", "Very poor"],
      },
      {
        key: "coping",
        label: "How do you primarily cope with stress?",
        type: "text",
        placeholder: "e.g. exercise, journaling, talking to friends, or avoidance",
      },
    ],
  },
];

export const calculateBMI = (weightKg, heightCm) => {
  const heightM = heightCm / 100;
  return (weightKg / (heightM * heightM)).toFixed(1);
};

export const getAreaById = (id) => HEALTH_AREAS.find((a) => a.id === id);
